uknowho/projects/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

app_name = 'projects'

urlpatterns = [
	# /projects/
    url(r'^$', views.IndexView.as_view(), name='index'),

    # /login/
    url(r'^login/$', auth_views.login, {'template_name': 'projects/login.html'}, name='login'),

    # /logout/
    url(r'^logout/$', auth_views.logout, {'template_name': 'projects/index.html'} ,name='logout'),

    # /register/
    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    # /dashboard/
    url(r'^dashboard/$', login_required(views.DashboardView.as_view(), login_url='/login/'), name='find'),

    # /profile/
    url(r'^profile/$', views.ProfileView.as_view(), name='profile'),

    #/createproj/
    url(r'^createproj/$', login_required(views.ProjectCreate.as_view(), login_url='/login/'), name="project_add"),

    #/search/hw/
    url(r'^search/(?P<type>[a-z]{2})/$', views.SearchByProjectType.as_view(),name="search_type"),

    #/projects/123/
    url(r'^projects/(?P<project_id>[0-9]+)/$', views.ProjectSubscribe.as_view(),name="projectSubscribe"),
    
]

uknowho/uknowho/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('projects.urls')),
    url(r'^projects/', include('projects.urls')),    
]

uknowho/projects/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings
from projects.choices import *


# Create your models here.
class Profile(models.Model):
    userid = models.CharField(default=' ', max_length=50)
    password = models.CharField(default=' ', max_length=50)
    country = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    firstName = models.CharField(max_length=50)
    lastName = models.CharField(max_length=50)
    course = models.CharField(max_length=50)
    university = models.CharField(max_length=50)
    #email = models.CharField(max_length=50)
    linkedIn = models.CharField(max_length=50)
    facebook = models.CharField(max_length=50)
    twitter = models.CharField(max_length=50)
    photo = models.CharField(max_length=20)

    def __str__(self):
        return self.firstName + ' ' + self.lastName + '/' + self.username

    #def get_absolute_url(self):
    #    return reverse('user:detail', kwargs={'pk': self.pk})

# Create a profile first.
class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=1000)
    photo = models.CharField(max_length=2000)
    duration = models.CharField(max_length=100)
    size = models.CharField(max_length=100)

    projectType = models.CharField(max_length=2, choices=projectType_CHOICES, default='ot')

    #postdate = models.DateField()
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default = None)

    def __str__(self):
        return self.title + ' ' + self.duration

    #return after form to. p.e. detail of project
    def get_absolute_url(self):
        return reverse('projects:index')

class Labels(models.Model):
    project=models.ForeignKey(Project, on_delete=models.CASCADE,default=None)
    label = models.CharField(max_length=30)#review


class Skill(models.Model):
    userid = models.ForeignKey(Profile, on_delete=models.CASCADE)
    skill = models.CharField(max_length=50)


class Language(models.Model):
    userid = models.ForeignKey(Profile, on_delete=models.CASCADE)
    language = models.CharField(max_length=40)


class Colaborators(models.Model):
    userid = models.ForeignKey(Profile, on_delete=models.CASCADE, default = None)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, default = None)

uknowho/projects/forms.py
from django.contrib.auth.models import User
from .models import Profile
from django import forms

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)
	username = forms.CharField()
	email = forms.CharField()

	class Meta:
		model = User
		fields = ['username', 'email', 'password']

uknowho/projects/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.template import RequestContext
from django.views import generic
from django.views.generic import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Project
from django.contrib.auth import authenticate, login
from .forms import UserForm
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.models import User
from .send_email import send_email
from projects.choices import *

class IndexView(generic.TemplateView):
	template_name = 'projects/index.html'


class LoginView(generic.TemplateView):
	template_name = 'projects/login.html'

class UserFormView(View):
    form_class = UserForm
    template_name = 'projects/register.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form}, RequestContext(request))

    def post(self, request):
        username = request.POST['username']
        password = request.POST['password']
        email = request.POST['email']
        user = User.objects.create_user(username, email, password)
        user.save()
        form = self.form_class(request.POST)

        user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('projects:index')

        return render(request, 'projects/index.html', {'form': form}, RequestContext(request))

@method_decorator(login_required(login_url='/login/'), name = 'dispatch' )
class DashboardView(generic.ListView):
	template_name = 'projects/dashboard.html'
	context_object_name = 'all_projects'

	def get_queryset(self):

		return Project.objects.all()

class ProfileView(generic.TemplateView):
	template_name = 'projects/profile.html'

@method_decorator(login_required(login_url='/login/'), name = 'dispatch' )
class ProjectCreate(CreateView):
	model = Project
	fields=['title','description','photo','duration','size','projectType','owner']

class SearchByProjectType(generic.ListView):
	model = Project
	template_name = 'projects/dashboard.html'
	context_object_name = 'all_projects'

	def get_queryset(self):
		projtype = self.kwargs['type']
		return Project.objects.filter(projectType=projtype)

class ProjectSubscribe(generic.ListView):
	model = Project
	template_name = 'projects/index.html'

	def get_queryset(self):
		projectID = self.kwargs['project_id']

		username = self.request.user.username
		email = self.request.user.email

		print("username" + username)

		print("project ID is " + projectID)

		project = Project.objects.get(pk=projectID)

		send_email(project.owner.email, username, email, project.title)

		return redirect('projects:index')

uknowho/projects/templates/projects/base.html
<html>
  <head>
    <meta charset="utf-8">

    {% load static %}

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet"/>
    <link rel="stylesheet" href="{% static 'projects/style.css'%}" />
    <link href="https://fonts.googleapis.com/css?family=Alfa+Slab+One" rel="stylesheet"/>
    <title>{% block title%} uknowho {% endblock %} </title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="{% static 'projects/js/main.js' %}"></script>
  </head>
  <body>
     <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'projects:index' %}">uknowho</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav">
              <li><a href="{% url 'projects:find'  %}">Find a Project</a></li>
              <li><a href="{% url 'projects:project_add'%}">Create a Project</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
           <li id="register"><a href="{% url 'projects:register' %}">Register</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
           <li id="login"><a href="{% url 'projects:login' %}">Login</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
           <li id="logout"><a href="{% url 'projects:logout' %}">Logout</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
           <li id="user"><a style="padding-top:10px;" href="{% url 'projects:profile' %}"><i class="fa fa-user" aria-hidden="true"></i> {{user.username}}</a></li>
          </ul>
        </div>
      </div>
    </nav>
    {% if user.is_authenticated %}
    <script type="text/javascript">
      $(".fa").css("display", "inline");
      $("#logout").css("display", "inline");
      $("#user").css("display", "inline");
      $("#login").css("display", "none");
      $("#register").css("display", "none");
    </script>
    {% else %}
    <script type="text/javascript">
      $(".fa").css("display", "none");
      $("#logout").css("display", "none");
      $("#ruser").css("display", "none");
      $("#login").css("display", "inline");
      $("#register").css("display", "inline");
    </script>
    {% endif %}
    {% block body %}{% endblock body %}

    <footer class="footer">
      <div class="container">
        <span class="text-muted">© 2017 uknowho</span>
        <span style="float:right" class="text-muted">Any doubts? <a>Contact us!</a></span>
      </div>
    </footer>
  </body>
</html>

uknowho/projects/templates/projects/dashboard.html
{% extends 'projects/base.html' %}

{% block title%} Dashboard {% endblock %}

{% block body %}
<style type="text/css">
  body {
    background-color: #eee;
  }
</style>
{% load staticfiles %}

<div id="dashCtn" class="container">
  <div class="row">
      <h1 class="text-center" style="color:black">Find a project!</h1>
      <div class="row" style="padding-left:20px;padding-right:20px;padding-top:10px;padding-bottom:20px;">
        <div class="col-md-2">
          <a href="/search/sw/"><button type="button" class="btn btn-default btn-block" style="background-color:#eee;color:black;"> Software </button></a>
        </div>
        <div class="col-md-2">
          <a href="/search/hw/"><button type="button" class="btn btn-default btn-block" style="background-color:#eee;color:black;"> Hardware </button></a>
        </div>
        <div class="col-md-2">
          <a href="/search/ar/"><button type="button" class="btn btn-default btn-block" style="background-color:#eee;color:black;"> Art </button></a>
        </div>
        <div class="col-md-2">
          <a href="/search/sp/"><button type="button" class="btn btn-default btn-block" style="background-color:#eee;color:black;"> Sport </button></a>
        </div>
        <div class="col-md-2">
          <a href="/search/ms/"><button type="button" class="btn btn-default btn-block" style="background-color:#eee;color:black;"> Music </button></a>
        </div>
        <div class="col-md-2">
          <a href="/search/ot/"><button type="button" class="btn btn-default btn-block" style="background-color:#eee;color:black;"> Others </button></a>
        </div>
      </div>
      <div class="list-group">
      {% for project in all_projects %}
        <a href="#" class="list-group-item">
            <div class="media col-md-3 dashCol">
              {% if project.photo == 'default' %}
              <img style="width:150px;padding-top:30px" class="media-object img-rounded img-responsive" src="{% with 'projects/images/icon_'|add:project.projectType|add:'.png' as image_static%} {% static image_static %}{% endwith %}" id="dash-img">
              {% else %}
              <img class="media-object img-rounded img-responsive"  src="http://placehold.it/350x250" alt="placehold.it/350x250" >
              {% endif %}
            </div>
            <div class="col-md-6 dashCol">
                <h4 class="list-group-item-heading"> {{project.title}} </h4>
                <p class="list-group-item-text"> {{project.description}} </p>
            </div>
            <div class="col-md-3 text-left dashCol">
                <p> <strong>Project Type:</strong> {{project.get_projectType_display}}</p>
                <p> <strong>Est. Duration:</strong> {{project.duration}}</p>
                <p> <strong>Nº of elements:</strong> {{project.size}} </p>
                <p> <strong>Submitted by:</strong> {{project.owner.username}} </p>
                <input class="btn btn-default btn-lg btn-block" type="button" style="color:white;" value="Start Creating!" onclick="location.href='{% url 'projects:projectSubscribe' project.pk %}'"/>
            </div>
        </a>
    {% endfor %}
    </div>
 	</div>
</div>
{% endblock body %}

uknowho/projects/templates/projects/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

uknowho/projects/templates/projects/index.html
{% extends 'projects/base.html' %}

{% block title%} Home {% endblock %}

{%load static%}

{% block body %}
    <div id="landingImage" class="container">
      <div class="jumbotron">
        <h1 style:"padding-top:30px;font-weight:bold;">Do you know anyone who?</h1>
        <h2><span class="brand">uknowho</span> is a website dedicated to everyone with the maker spirit.
        Join a Project and meet the team or just simply scroll through projects
        for ideas and inspiration.</h2>
        <div id="jumbotronButtons">
          <a href="{% url 'projects:find' %}"><button type="button" class="jumbotronButton">Find Projects</button></a>
          <a href="{% url 'projects:project_add'%}"><button type="button" class="jumbotronButton">Create Projects</button></a>
        </div>
      </div>
    </div>
    <div class="container" id="categoryItems">
        <div class="row">
          <div style="padding-bottom:40px;font-size:1.4em" class="col-md-12">
            Choose your project category
          </div>
        </div>
        <div class="row">
            <div class="col-md-3">
              <a href="/search/sw/"><img class="categoryItem" width="140px" src="{% static 'projects/images/icon_sw.png' %}" /></a>
              <p>Programming</p>
            </div>
            <div class="col-md-3">
              <a href="/search/hw/"><img class="categoryItem" width="140px" src="{% static 'projects/images/icon_hw.png' %}" /></a>
              <p>Electronics</p>
            </div>
            <div class="col-md-3">
              <a href="/search/ar/"><img class="categoryItem" width="140px" src="{% static 'projects/images/icon_ar.png' %}" /></a>
              <p>Art</p>
            </div>
            <div class="col-md-3">
              <a href="/search/ot"><img class="categoryItem" width="140px" src="{% static 'projects/images/icon_ot.png' %}" /></a>
              <p>And more!</p>
            </div>
        </div>
    </div>
    <div style="background-color: gray; padding: 40px; color:white">
      <div class="container">
          <div class="row">
            <div style="text-align:center;padding-bottom:30px;font-size:2.1em" class="col-md-12">
            Where the idea came from?
          </div>
      </div>
    </div>
      <div class="row">
        <div class="col-md-12">
          <p style="text-align:center;font-size:20px; padding-top:10px;">As students
          and makers we often need to work on group projects. Unfortunately it is
          possible that not everyone on the team share the same commitement and
          even goals. As such knowing a bit about who will be on your team is a
          big help for the success of your projects.</p>
        </div>
      </div>
    </div>
    <div style="padding-bottom: 150px; padding-top: 40px;" class="container">
      <div class="row">
          <div style="text-align:center;padding-bottom:30px;font-size:2.1em" class="col-md-12">
            About Hackerschool
          </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <p style="text-align:center;font-size:20px; padding-top:10px;">Hackerscool
          is an independent student group that dedicates its time to teaching
          the community, through workshops and events, and developing innovative
          projects.</p>
        </div>
      </div>
    </div>
{% endblock body %}

uknowho/projects/templates/projects/login.html
{% extends 'projects/base.html' %}

{% block title%} Login {% endblock %}

{% block body %}
 	<!-- LOGIN BOX -->
 	<style type="text/css">
 		body {
 			background-color: #eee;
 		}
 	</style>
	<div class="container loginCtn" method="post">
		<form class="form-signin" action="{% url 'projects:login' %}" method='post'>
			{% csrf_token %}
			<h1 style="text-align:center;" class="text-muted">Login</h1>
			{% if error_message %}
				<p><strong>{{error_message}}</strong></p>
			{% endif %}
			<input type="text" class="form-control" placeholder="username" name="username" required="required" autofocus="">
			<input type="password" class="form-control" placeholder="Password" name="password" required="required">
			<button class="btn btn-lg btn-primary btn-block" type="submit">
				Login
			</button>
			<br>
			<p><a>Forgot your password?</a></p>
		</form>
	</div>
{% endblock body %}

uknowho/projects/templates/projects/profile.html
{% extends 'projects/base.html' %}

{% block body %}
<div style="background-color: gray; padding: 40px; color:white">
	<div class="container">
		<div class="row">
			<div style="text-align:center;padding-bottom:30px;font-size:2.1em" class="col-md-12">
				You know why?
			</div>
		</div>
	</div>
</div>
{% endblock body %}

uknowho/projects/templates/projects/project_form.html
{%extends 'projects/base.html'%}

{% block body %}
<style type="text/css">
    body {
      background-color: #eee;
    }
</style>
<div class="container createCtn">
    <form class="form-horizontal" action="" method="post">
       <h1 style="padding-bottom: 20px; text-align:center">Start sharing your idea!</h1>
      {%csrf_token%}
      {% for field in form%}
      <div class="row">
          <div class="col-md-3"><label>{{field.label_tag}}</label></div>
          <div style="padding-bottom:20px" class="col-md-9"> <div>{{field}}</div></div>
          <span class="text-danger small"> {{field.errors}}</span>
      </div>
      {% endfor %}
      <button class="btn btn-lg btn-primary btn-block" type="submit">
        Post project
      </button>
    </form>
</div>
{% endblock %}

uknowho/projects/templates/projects/register.html
{% extends 'projects/base.html' %}

{% block title%} Register {% endblock %}

{% block body %}

 	<!-- REGISTER BOX -->
 	<style type="text/css">
 		body {
 			background-color: #eee;
 		}
 	</style>
 	<div class="container loginCtn">


		<form class="form-signin" role='form' action="" method="post" enctype="multipart/form-data">
			{% csrf_token %}
			<h1 style="text-align:center;" class="text-muted">Register</h1>
			<input type="text" name="username" class="form-control" placeholder="Name" required="required" autofocus="">
			<input type="email" name="email" class="form-control" placeholder="Email address" required="required" >
			<input type="password" name="password" class="form-control" placeholder="Password" required="required">
			<button class="btn btn-lg btn-primary btn-block" type="submit">
				Register
			</button>
		</form>

	</div>
{% endblock body %}

uknowho/projects/templates/user/base.html
<html>
  <head>
    <meta charset="utf-8">

    {% load static %}

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet"/> 
    <link rel="stylesheet" href="{% static 'projects/style.css'%}" />
    <link href="https://fonts.googleapis.com/css?family=Alfa+Slab+One" rel="stylesheet"/> 
    <title>uknowho - Home</title>
  </head>
  <body>
     <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'projects:index' %}">uknowho</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav">
              <li><a href="#">Find</a></li>
              <li><a href="#">Create</a></li>
          </ul>

          {% if user.is_authenticated %}           
             <ul class="nav navbar-nav navbar-right">
               <li id="login"><a href="{% url 'projects:logout' %}">Logout</a></li>
             </ul> 
             <ul class="nav navbar-nav navbar-right">
               <li id="login"><a href="#">{{user.username}}</a></li>
             </ul> 
          {% else %}
            <ul class="nav navbar-nav navbar-right">
             <li id="login"><a href="{% url 'projects:register' %}">Register</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
             <li id="login"><a href="{% url 'projects:login' %}">Login</a></li>
            </ul>
          {% endif %}
        </div>
      </div>
    </nav> 
    {% block body %}{% endblock body %}

    <footer class="footer">
      <div class="container">
        <span class="text-muted">Place sticky footer content here.</span>
      </div>
    </footer>
  </body>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="{% static 'projects/js/main.js' %}"></script>
</html>

uknowho/projects/templates/user/details.html
{% extends 'user/base.html' %}

{% block body %}

    <ul>
        {% for user in object_list %}
            <li>{{ user.first_name }}</li>
        {% endfor %}
    </ul>

{% endblock %}